from .face_recognizer import FaceRecognizer
from .object_recognizer import ObjectRecognizer
from .qrcode_recognizer import QRCodeRecognizer
from .hotword_recognizer import HotwordRecognizer
from .speech_recognizer_snowboy import SpeechRecognizer